import "./globals.css";

import { Playfair_Display } from "next/font/google";

const playFair = Playfair_Display({
  variable: "--play-font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${playFair.variable}`}>
      <body className="tw-bg-slate-700">{children}</body>
    </html>
  );
}
